version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '8000:8000'
  frontend:
    build: ./front
    container_name: front
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true
